#对V1,加入严重遮挡样本的训练
base_classname: vehicle                                  # 一级类型名称
num_classes: 3                                          # 类别数量
remove_empty_images: true                               # 删除空图片
shuffle: true                                           # 打乱图片顺序
remove_zh_image_path: true                              # 删除中文路径图片
class_mappers: # 目标类别转换器
  - id: null                                                  # 空类, 用于删除样本
    match_condiction: # 为真值, 则匹配成功
      or: # 以下任一条件为真, 则输出真
        - contains: { attrs: { ignore: "yes" } }                            # 包含{"attrs": {"ignore": "yes"}}
        - contains: { attrs: { confidence: Low } }                          # 包含{"attrs": {"confidence": "Low"}}
        - contains: { attrs: { confidence: VeryLow } }                      # 包含{"attrs": {"confidence": "VeryLow"}}
        - and:
            - range: { field: $BBOX_HEIGHT, lt: 12 }                          # bbox高度 < 55
            - range: { field: $BBOX_WIDTH, lt: 12 }                           # bbox宽度 < 18
        - contains: { attrs: { type: Bike } }                               # 包含{"attrs": {"type": "Bike"}}
        - contains: { attrs: { type: Motercycling } }                       # 包含{"attrs": {"type": "Motercycling"}}
        - contains: { attrs: { type: Motorcycle } }                         # 包含{"attrs": {"type": "Motorcycle"}}
        - contains: { attrs: { occlusion: invisible } }
        - contains: { attrs: { occlusion: invisible_d } }
        - contains: { attrs: { part: ignore } }
        - contains: { attrs: { part: full } }
  - id: 1
    name: head
    match_condiction: # 为真值, 则匹配为该类别
      or:
        - contains: { attrs: { part: head } }                # 包含{"attrs": {"occlusion": "full_visible"}}
        - contains: { attrs: { type: Vehicle_light } }
  - id: 2
    name: rear
    match_condiction: # 为真值, 则匹配为该类别
      contains: { attrs: { part: rear } }                    # 包含{"attrs": {"occlusion": "occluded"}}
  - id: 3
    name: unknown
    match_condiction: # 为真值, 则匹配为该类别
      contains: { attrs: { part: unknown } }                    # 包含{"attrs": {"occlusion": "occluded"}}
