base_classname: vehicle                                 # 一级类型名称
num_classes: 7                                          # 类别数量
remove_empty_images: true                               # 删除空图片
shuffle: true                                           # 打乱图片顺序
class_mappers:                                          # 目标类别转换器
- id: null                                                  # 空类, 用于删除样本
  match_condiction:                                         # 为真值, 则匹配成功
    or:
    - contains: {attrs: {ignore: "yes"}}                    # 包含{"attrs": {"ignore": "yes"}}
    #- and:
    #  - range: {field: $BBOX_WIDTH, lt: 200}
    #  - contains: {attrs: {occlusion: heavily_occluded}}
    #  - or:
    #    - range: {field: $BBOX_X1, gt: 5}
    #    - range: {field: $BBOX_Y2, lt: 1270}
    #    - contains: {attrs: {occlusion: heavily_occluded}}              # 包含{"attrs": {"occlusion": "heavily_occluded"}}
    - contains: {attrs: {occlusion: heavily_occluded}}
    - contains: {attrs: {occlusion: invisible}}                     # 包含{"attrs": {"occlusion": "invisible"}}
    - range: {field: $BBOX_HEIGHT, lt: 25}                          # bbox高度 < 25   # 0323
    - range: {field: $BBOX_WIDTH, lt: 25}                           # bbox宽度 < 25   # 0323
- id: 1
  name: Bus
  match_condiction:
    contains: {attrs: {type: Bus}}
  upsample: 30.97
- id: 2
  name: Small_Medium_Car
  match_condiction:
    or:
      - contains: {attrs: {type: Sedan_Car}}
      - contains: {attrs: {type: SUV}}
      - contains: {attrs: {type: MiniVan}}
      - contains: {attrs: {type: Small_Medium_Car}}
  upsample: 1
- id: 3
  name: Trucks
  match_condiction:
    or:
      - contains: {attrs: {type: BigTruck}}
      - contains: {attrs: {type: SmallTruck}}
      - contains: {attrs: {type: Trucks}}
  upsample: 5.83
- id: 4
  name: Motors
  match_condiction:
    or:
      - contains: {attrs: {type: Motor-Tricycle}}
      - contains: {attrs: {type: Tricycle}}
      - contains: {attrs: {type: SmallTruckWithPerson}}
      - contains: {attrs: {type: Motors}}
  upsample: 35.25
- id: 5
  name: Special_vehicle
  match_condiction:
    contains: {attrs: {type: Special_vehicle}}
  upsample: 40.05
- id: 6
  name: Tiny_car
  match_condiction:
    contains: {attrs: {type: Tiny_car}}
  upsample: 82.3
- id: 7
  name: Lorry
  match_condiction:
    contains: {attrs: {type: Lorry}}
  upsample: 33.4
